name: Build

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Checkout GitHub
      uses: actions/checkout@v3
    
    - name: Build
      run: mingw32-make

    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.exe
        tag_name: v1.1.0
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}