name: Build

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Checkout GitHub
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: .NET Build
      run: dotnet publish

    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: bin/Release/net6.0-windows/win-x64/publish/*.exe
        tag_name: v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}